server:
  port: 8888

jwt:
  secret: ThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExample
  #expiration: 86400000
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
    jpa:
      repositories:
        enabled: true

cloud:
  aws:
    s3:
      bucketName: project-03
    credentials:
      accessKey: AKIAT7D6YZN4ZS2RPMQU
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/